### ISSUE TITLE
Allow language-luajit as an optional dependency instead of language-lua

### ISSUE THREAD

**Issue by DanielPower** [rm-code/love-atom#14]

**Comment by rm-code** [comment]
Thanks for the suggestion. I'm currently a bit occupied with real life and my main development machine broke down, so it'll be a while before I can take a look into it (probably August).

**Comment by pablomayobre** [comment]
I think that dropping the dependency on the language package should be better.

Dependencies should be packages that are required for this package to work. But the language package isn't and it can be installed by the user later on.

A suggestion on the readme would be better than having `language-lua` as a dependency

**Comment by rm-code** [comment]
> Dependencies should be packages that are required for this package to work. But the language package isn't and it can be installed by the user later on.

Yes I agree. IIRC it was needed to get the snippets back to work in one of the earlier versions, but I might be wrong.

Anyway, I'll remove the dependency.

**Comment by rm-code** [comment]
I decided against removing `language-lua` as a dependency for now. I updated the README with instructions on how to use a custom language package.

The main reason is that `language-lua` is the standard for working with Lua in Atom and love-atom requires a language package of some kind. Removing it would mean that other users would have to manually install `language-lua`.
