### ISSUE TITLE
First argument ommited

### ISSUE THREAD

**Issue by rm-code** [rm-code/love-atom#15]
<img width="749" alt="bildschirmfoto 2017-10-24 um 18 44 00" src="https://user-images.githubusercontent.com/11627131/31956330-6211ca84-b8eb-11e7-9253-7049840d4522.png">

This should start with `textstring`. Looking at the love-api this also should have generated correctly.

**Comment by pablomayobre** [comment]
All the Type methods, take a `self` argument, even if that is not clearly documented.

The colon syntax in Lua always translates the same way:
```lua
object:method()
object.method(object)
```
Regardless of `object` being a `table` or a  `userdata`

This means that, if needed, you could do `image.getWidth(otherimage)`
