### ISSUE TITLE
Dependency to language-lua

### ISSUE THREAD

**Issue by echox** [rm-code/love-atom#4]
Hi,
I tried to get the autocompletion running and it simply didn't work.
Checked the console for "Activate LOVE-Provider. Baby don't hurt me!" which was there.

After searching for any configuration I simply added the "language-lua" package in addition and now the autocompletion works.
If think most of the time people will have "language-lua" installed if they work with Lua, but if its really a dependency, it should be mentioned in the README.md or added to the plugins dependencies which will get automatically installed.

**Comment by rm-code** [comment]
Adding it to the plugin dependencies makes the most sense. Are you up for a pull request? 

If not, I'll see if I get around changing it myself later today.

**Comment by echox** [comment]
Sure, please test :-)

https://github.com/echox/love-atom/pull/1

**Comment by rm-code** [comment]
@echox I just pushed a commit which makes use of the atom-package-deps package. It would be cool if you could test it.

On my system it installed language-lua automatically 👍

**Comment by rm-code** [comment]
Published release 2.3.0 - Seems to work fine :)

Thanks for the suggestions @echox!
