### ISSUE TITLE
integrated Debugger

### ISSUE THREAD

**Issue by SiENcE** [rm-code/love-atom#6]
Visual Studio Code has a Lua Debugger.

Maybe it can be adapted to Atom!?

https://marketplace.visualstudio.com/items?itemName=devCAT.lua-debug

**Comment by rm-code** [comment]
I'd love to have a debugger in Atom, but I haven't looked at creating a package for it yet... It probably wouldn't hurt to take a look at how ZeroBrane does it.

I use https://github.com/slembcke/debugger.lua on the CLI from time to time.

**Comment by rm-code** [comment]
@SiENcE I'm closing this as it doesn't really fit into this repository. 
Maybe you could ask the author of the LOVE-IDE packages?

**Comment by pablomayobre** [comment]
I'll make a package one day! I promise
